### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by grug** [knegusen/enzyme-redux#2]
There are currently no typings in @types/enzyme-redux. This makes it a pain to use this useful library for typescript projects.

**Comment by knegusen** [comment]
I'm not using TypeScript personally, so I don't have time to maintain type definitions for it. Would be better to submit to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) instead.

**Comment by grug** [comment]
Thanks for responding to this. It's not really an issue for DefinitelyTyped - it'd be up to someone (ideally the owner/maintainer) of the library to submit typings. However, you've stated you don't use Typescript and don't have the time to maintain typings for the project so that makes sense :)
