### ISSUE TITLE
mountWithStore is missing in npm package

### ISSUE THREAD

**Issue by Tuizi** [knegusen/enzyme-redux#7]
After installing enzyme-redux from npmjs (version 0.2.0), it looks like the release file in `dist` folder is incorrect. This file contains only methods: `shallowWithStore` & `shallowWithState`. 

`mountWithStore` and `mountWithState` functions are missing, there is the documentation but the code is not included in the bundled file.

**Comment by knegusen** [comment]
Thank you! Didn't have build step in prepublish. Fixed in https://github.com/knegusen/enzyme-redux/releases/tag/v0.2.1
